import json
import os
import textwrap
from dataclasses import dataclass

from google import genai
from google.genai import types
from rich.console import Console, Group
from rich.panel import Panel
from rich.rule import Rule
from rich.text import Text

from alerts import Alert
from tools import DIAGNOSTIC_TOOL_DECLARATIONS, execute_diagnostic_tool

console = Console()

# The agent's persona and output contract.
# Critically: we only give it diagnostic (read-only) tools.
# Remediation tools are withheld — the agent proposes, never acts.
SYSTEM_PROMPT = """You are an expert SRE (Site Reliability Engineer) agent.

Your task:
1. Use the available tools to gather diagnostic data about the incoming alert.
2. Identify the root cause with evidence from the data you collected.
3. Propose ONE specific remediation action.

Available remediation actions you can propose (you cannot call these — just name them):
- restart_service(service)                              moderate risk, quick fix for memory leaks
- scale_service(service, replicas)                      low risk, good for CPU/traffic spikes
- kill_long_running_queries(database, older_than_seconds)  moderate risk, fixes pool exhaustion
- run_vacuum(database)                                  low risk, reclaims disk space
- rollback_deployment(service, version)                 high risk, use only if recent deploy caused it

Once you have gathered sufficient evidence, respond ONLY with a JSON object:
{
  "diagnosis": "What is wrong and how severe",
  "root_cause": "The underlying technical cause with evidence",
  "proposed_action": {
    "tool": "tool_name",
    "parameters": {"param": "value"},
    "description": "Human-readable description of what this action does",
    "target_service": "the exact service name or database being modified"
  },
  "rollback_plan": {
    "tool": "tool_name",
    "parameters": {"param": "value"},
    "description": "How to undo this action if it makes things worse"
  },
  "confidence": 0.85
}
"""


@dataclass
class RemediationProposal:
    """Represents a structured remediation plan generated by the agent."""

    diagnosis: str
    root_cause: str
    proposed_action: dict  # keys: tool, parameters, description, target_service
    rollback_plan: dict  # keys: tool, parameters, description
    confidence: float


class DiagnosisAgent:
    """
    Runs a multi-turn ReAct-style loop: the model observes the alert, calls
    diagnostic tools to gather evidence, then produces a structured remediation
    proposal when it has enough information.
    """

    MAX_STEPS = 10  # guard against infinite tool-calling loops

    def __init__(self):
        """Initialises the Gemini client and wraps diagnostic declarations in a Tool object."""
        self.client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
        self.tools = [types.Tool(function_declarations=DIAGNOSTIC_TOOL_DECLARATIONS)]

    def run(self, alert: Alert) -> RemediationProposal:
        """Drives the agentic loop until the model produces a JSON remediation proposal.

        Each iteration: call the model → if it requests tools, execute them and feed results back;
        if it produces text with no tool calls, parse and return the proposal.
        Raises RuntimeError if MAX_STEPS is exhausted without a proposal.
        """
        contents = [
            types.Content(
                role="user",
                parts=[types.Part(text=self._format_alert(alert))],
            )
        ]

        for step in range(self.MAX_STEPS):
            # --- Style Model Input ---
            input_elements = []
            if step == 0:
                indent = " " * 8
                wrapped = textwrap.fill(
                    SYSTEM_PROMPT, width=82, subsequent_indent=indent
                )
                input_elements.append(
                    Text.assemble(("SYSTEM: ", "dim"), (wrapped, "dim"))
                )
                input_elements.append(Rule(style="bright_black"))

            for msg in contents:
                role = "user" if msg.role == "user" else "assistant"
                content = ""
                for part in msg.parts:
                    if part.text:
                        content += part.text
                    elif part.function_call:
                        content += f"Function Call: {part.function_call.name}({part.function_call.args})"
                    elif part.function_response:
                        content += f"Function Response: {part.function_response.name} -> {part.function_response.response}"

                if role == "user":
                    label_style = "bold blue"
                    content_style = "blue"
                else:
                    label_style = "bold green"
                    content_style = "green"

                indent = " " * (len(role) + 2)
                wrapped = textwrap.fill(content, width=82, subsequent_indent=indent)
                input_elements.append(
                    Text.assemble(
                        (f"{role.upper()}: ", label_style), (wrapped, content_style)
                    )
                )
                input_elements.append(Rule(style="bright_black"))

            if input_elements:
                input_elements.pop()  # Remove trailing rule

            console.print(
                Panel(
                    Group(*input_elements),
                    title="[bold bright_black]Model Input[/bold bright_black]",
                    border_style="bright_black",
                    padding=(1, 2),
                )
            )
            console.print()

            # Model decides whether to call tools or provide the final diagnosis
            response = self.client.models.generate_content(
                model="gemini-2.5-flash",
                contents=contents,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_PROMPT,
                    tools=self.tools,
                    temperature=0.1,  # low temp for deterministic tool-calling decisions
                ),
            )

            candidate = response.candidates[0]
            # Append model turn to history before processing
            contents.append(candidate.content)

            # --- Style Model Response ---
            response_text = ""
            for part in candidate.content.parts:
                if part.text:
                    response_text += part.text
                elif part.function_call:
                    response_text += f"Function Call: {part.function_call.name}({part.function_call.args})"

            wrapped_response = textwrap.fill(
                response_text, width=82, subsequent_indent="           "
            )
            response_content = Text.assemble(
                ("ASSISTANT: ", "bold green"), (wrapped_response, "italic")
            )

            console.print(
                Panel(
                    response_content,
                    title="[bold bright_black]Model Response[/bold bright_black]",
                    border_style="bright_black",
                    padding=(1, 2),
                    highlight=False,
                )
            )
            console.print()

            function_calls = [p for p in candidate.content.parts if p.function_call]
            text_parts = [p for p in candidate.content.parts if p.text]

            if not function_calls:
                # No more tool calls — the model has finished diagnosing
                full_text = "".join(p.text for p in text_parts)
                return self._parse_proposal(full_text)

            # Execute every tool the model requested and collect results
            tool_result_parts = []
            for part in function_calls:
                fc = part.function_call
                args = dict(fc.args)
                console.print(f"  [cyan]→ Tool:[/cyan] [bold]{fc.name}[/bold]  {args}")

                result = execute_diagnostic_tool(fc.name, args)
                console.print(f"  [dim]  ← {json.dumps(result)[:200]}[/dim]")

                tool_result_parts.append(
                    types.Part(
                        function_response=types.FunctionResponse(
                            name=fc.name,
                            response=result,
                        )
                    )
                )

            # Feed results back as a user turn so the loop can continue
            contents.append(types.Content(role="user", parts=tool_result_parts))

        raise RuntimeError(
            "Agent exceeded max steps without producing a remediation proposal"
        )

    def _format_alert(self, alert: Alert) -> str:
        """Formats the alert as a structured plain-text block for the model's first user turn."""
        return (
            f"INCOMING ALERT\n"
            f"ID:          {alert.id}\n"
            f"Service:     {alert.service}\n"
            f"Type:        {alert.alert_type}\n"
            f"Severity:    {alert.severity}\n"
            f"Description: {alert.description}\n"
            f"Metadata:    {json.dumps(alert.metadata)}\n\n"
            f"Diagnose this alert and propose a remediation."
        )

    def _parse_proposal(self, text: str) -> RemediationProposal:
        """Extracts and deserialises the JSON proposal from the model's final response.

        Handles three formats: raw JSON, ```json fences, and plain ``` fences.
        Falls back to scanning for the outermost { } pair if preamble text precedes the JSON.
        """
        # Strip markdown code fences that the model sometimes wraps around JSON
        if "```json" in text:
            text = text.split("```json")[1].split("```")[0]
        elif "```" in text:
            text = text.split("```")[1].split("```")[0]

        # Fallback: find the outermost JSON object if the model added preamble text
        text = text.strip()
        if not text.startswith("{"):
            start = text.find("{")
            end = text.rfind("}") + 1
            if start != -1 and end > start:
                text = text[start:end]

        data = json.loads(text)
        return RemediationProposal(
            diagnosis=data["diagnosis"],
            root_cause=data["root_cause"],
            proposed_action=data["proposed_action"],
            rollback_plan=data["rollback_plan"],
            confidence=data["confidence"],
        )
