#!/usr/bin/env python3
"""
Complex Orchestrator and Specialist Pattern
===========================================
Demonstrates multi-agent message passing with deeply nested schema contracts.

Architecture:
1. Orchestrator: Central controller managing workflow and state.
2. Planner Specialist: Breaks down a topic into a Blueprint (list of SectionPlans).
3. Researcher Specialist: (Iterative) Researched each SectionPlan into SectionResearch.
4. Writer Specialist: Synthesizes final FinalDocument from research and blueprint.

Concept: Multi-agent systems fail at the interface.
         Deeply nested schema contracts are critical for stability in complex loops.
"""

import json
import os
import textwrap
import time

from google import genai
from google.genai import types
from pydantic import BaseModel, ValidationError
from rich.console import Console
from rich.markup import escape
from rich.panel import Panel
from rich.rule import Rule
from rich.table import Table

console = Console()

# ── Config ────────────────────────────────────────────────────────────────────

MODEL = "gemini-2.5-flash"

try:
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
except KeyError:
    console.print(
        "[bold red]Error:[/bold red] GEMINI_API_KEY environment variable not set."
    )
    raise SystemExit(1)

USER_REQUEST = "The role of Rust in systems programming for 2026"
API_CALL_DELAY = 1.0


# ── Schema Contracts ──────────────────────────────────────────────────────────

class SectionPlan(BaseModel):
    """Sub-task plan for a specific section."""
    title: str
    research_goals: list[str]


class Blueprint(BaseModel):
    """The master plan generated by the Planner Specialist."""
    title: str
    sections: list[SectionPlan]


class Fact(BaseModel):
    """A granular piece of research data."""
    claim: str
    source: str
    confidence: float  # 0.0 to 1.0


class SectionResearch(BaseModel):
    """The research results for a single section."""
    section_title: str
    facts: list[Fact]
    key_terms: list[str]


class ContentSection(BaseModel):
    """A section in the final document."""
    title: str
    body: str


class FinalDocument(BaseModel):
    """The synthesized whitepaper from the Writer Specialist."""
    title: str
    introduction: str
    body_sections: list[ContentSection]
    conclusion: str
    word_count: int


# ── Logging Helpers ───────────────────────────────────────────────────────────

def log_model_input(label: str, prompt: str) -> None:
    console.print(Rule(f"[bold blue]Model Input: {label}[/bold blue]", style="blue"))
    label_tag = "[bold blue]user[/bold blue]"
    wrapped = textwrap.fill(prompt, width=88, subsequent_indent="         ")
    console.print(f"  {label_tag}:    [blue]{wrapped}[/blue]")
    console.print()


def log_model_output(response_text: str) -> None:
    console.print(Rule("[bold green]Model Response[/bold green]", style="green"))
    console.print(f"[italic]{response_text}[/italic]", highlight=False)
    console.print()


# ── Specialist Agents ─────────────────────────────────────────────────────────

def planner_specialist(topic: str) -> Blueprint:
    """Planner: Breaks down a broad topic into researchable sections."""
    prompt = (
        "You are a technical strategist. Plan a whitepaper outline for the following topic.\n\n"
        f"Topic: {topic}\n\n"
        "Break it into 2 distinct sections. For each section, define 2 research goals.\n"
        "Return JSON matching the Blueprint schema."
    )
    
    log_model_input("Planner Specialist", prompt)
    
    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=Blueprint,
        ),
    )
    
    log_model_output(response.text)
    return Blueprint.model_validate_json(response.text)


def researcher_specialist_v1(plan: SectionPlan) -> SectionResearch:
    """Researcher v1: Compliant specialist that provides structured facts."""
    prompt = (
        f"You are a deep-dive researcher. Research the section: '{plan.title}'.\n"
        f"Goals: {', '.join(plan.research_goals)}\n\n"
        "Provide 2 structured facts with sources and confidence scores (0.0-1.0). "
        "Also list 2 technical key terms.\n"
        "Return JSON matching the SectionResearch schema."
    )
    
    log_model_input("Researcher Specialist (v1)", prompt)
    
    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=SectionResearch,
        ),
    )
    
    log_model_output(response.text)
    return SectionResearch.model_validate_json(response.text)


def researcher_specialist_v2_broken(plan: SectionPlan) -> dict:
    """Researcher v2: Broken specialist that changes the schema (facts are strings)."""
    prompt = (
        f"You are a researcher. Summarize findings for: '{plan.title}'.\n"
        "Return JSON with 'section_title', 'facts' (list of strings, not objects), "
        "and 'key_terms' (list of strings).\n"
        "DO NOT use the standard Fact object structure."
    )
    
    log_model_input("Researcher Specialist (v2-BROKEN)", prompt)
    
    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
        ),
    )
    
    log_model_output(response.text)
    return json.loads(response.text)


def writer_specialist(topic: str, blueprint: Blueprint, research_data: list[SectionResearch]) -> FinalDocument:
    """Writer: Synthesizes research and blueprint into a final whitepaper."""
    
    research_summary = ""
    for r in research_data:
        facts_str = "\n".join([f"- {f.claim} (Source: {f.source}, Confidence: {f.confidence})" for f in r.facts])
        research_summary += f"Section: {r.section_title}\nFacts:\n{facts_str}\n\n"

    prompt = (
        f"You are a professional technical writer. Write a whitepaper on '{topic}'.\n\n"
        f"Use this blueprint: {blueprint.model_dump_json()}\n\n"
        f"And this research data:\n{research_summary}\n\n"
        "Write a structured document with an introduction, body sections (as planned), and a conclusion.\n"
        "Return JSON matching the FinalDocument schema."
    )
    
    log_model_input("Writer Specialist", prompt)
    
    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=FinalDocument,
        ),
    )
    
    log_model_output(response.text)
    return FinalDocument.model_validate_json(response.text)


# ── Orchestrator ──────────────────────────────────────────────────────────────

def orchestrate(use_broken_specialist: bool = False) -> FinalDocument:
    """
    Orchestrator: Coordinates the multi-agent pipeline.
    """
    # Step 1: Planning
    console.print("[bold cyan]>> Orchestrator: Dispatching to Planner Specialist[/bold cyan]")
    blueprint = planner_specialist(USER_REQUEST)
    
    # Step 2: Iterative Research
    all_research = []
    for i, section in enumerate(blueprint.sections):
        console.print(f"[bold cyan]>> Orchestrator: Researching Section {i+1}/{len(blueprint.sections)}: {section.title}[/bold cyan]")
        time.sleep(API_CALL_DELAY)
        
        if use_broken_specialist:
            raw_data = researcher_specialist_v2_broken(section)
            console.print(f"[bold yellow]  Orchestrator: Validating response against SectionResearch contract...[/bold yellow]\n")
            try:
                research = SectionResearch.model_validate(raw_data)
                all_research.append(research)
            except ValidationError as e:
                display_validation_failure(e, raw_data, SectionResearch)
                raise
        else:
            research = researcher_specialist_v1(section)
            all_research.append(research)
            
    # Step 3: Writing
    console.print("[bold cyan]>> Orchestrator: Dispatching to Writer Specialist[/bold cyan]")
    time.sleep(API_CALL_DELAY)
    final_doc = writer_specialist(USER_REQUEST, blueprint, all_research)
    
    return final_doc


# ── Display Helpers ───────────────────────────────────────────────────────────

def display_validation_failure(error: ValidationError, raw: dict, model_class: type[BaseModel]) -> None:
    console.print(Rule("[bold red]Contract Violation — ValidationError[/bold red]", style="red"))
    console.print()

    expected_fields = set(model_class.model_fields.keys())
    received_fields = set(raw.keys())

    table = Table(title=f"Field Mapping for {model_class.__name__}", show_lines=True)
    table.add_column("Field Name", style="bold")
    table.add_column("Status", justify="center")
    table.add_column("Details", style="dim")

    for field_name, field in model_class.model_fields.items():
        present = field_name in raw
        status = "[green]OK[/green]" if present else "[red]MISSING[/red]"
        details = str(field.annotation).replace("typing.", "")
        table.add_row(field_name, status, details)
    
    for extra in received_fields - expected_fields:
        table.add_row(extra, "[yellow]EXTRA[/yellow]", "Unexpected field")

    console.print(table)
    console.print()

    console.print("[bold red]Pydantic Errors:[/bold red]")
    for err in error.errors():
        loc = " -> ".join(str(l) for l in err["loc"])
        console.print(f"  [dim]•[/dim] [bold]{loc}[/bold]: [red]{err['msg']}[/red]")
    console.print()


def display_final_document(doc: FinalDocument) -> None:
    console.print(Rule("[bold green]Final Whitepaper[/bold green]", style="green"))
    console.print(Panel(f"[bold]{doc.title}[/bold]", border_style="green", expand=False))
    console.print(f"\n[bold]Introduction:[/bold]\n{textwrap.fill(doc.introduction, width=88)}")
    
    for section in doc.body_sections:
        console.print(f"\n[bold]Section: {section.title}[/bold]")
        console.print(textwrap.fill(section.body, width=88))
        
    console.print(f"\n[bold]Conclusion:[/bold]\n{textwrap.fill(doc.conclusion, width=88)}")
    console.print(f"\n[dim]Word count: {doc.word_count}[/dim]")
    console.print()


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    console.print(
        Panel.fit(
            "[bold yellow]Complex Orchestrator and Specialist Pattern[/bold yellow]\n"
            "[dim]Iterative multi-agent pipeline with nested schema contracts.[/dim]\n"
            f'[dim]Topic: "{USER_REQUEST}"[/dim]',
            border_style="yellow",
        )
    )
    console.print()

    # Phase 1: Success
    console.print(Rule("[bold]Phase 1 — Contract Honored[/bold]", style="white"))
    console.print()
    
    try:
        doc = orchestrate(use_broken_specialist=False)
        display_final_document(doc)
    except Exception as e:
        console.print(f"[bold red]Phase 1 Error:[/bold red] {e}")

    # Phase 2: Failure
    console.print(Rule("[bold]Phase 2 — Contract Broken[/bold]", style="white"))
    console.print()
    console.print("[dim]The Researcher Specialist starts returning 'facts' as a list of strings instead of objects.[/dim]\n")
    
    try:
        orchestrate(use_broken_specialist=True)
    except ValidationError:
        console.print("[bold green]✓ Orchestrator successfully caught the contract violation.[/bold green]")
    except Exception as e:
        console.print(f"[bold red]Unexpected error in Phase 2:[/bold red] {e}")

    console.print(Rule("[bold yellow]End of Demonstration[/bold yellow]", style="yellow"))


if __name__ == "__main__":
    main()
